{
 "title": "Docker Engine Experemental",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "engine_daemon_engine_info" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes/engine_daemon_engine_memory_bytes*100"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "description": "The number of bytes of memory that the host system of the engine has",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "description": "Count of running containers",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "description": "The number of cpus that the host system of the engine has",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus" }
   ]
  },
  {
   "title": "Image Builds",
   "type": "graph",
   "description": "Number of triggered image builds",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(builder_builds_triggered_total{instance=~'$instance'}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Container Actions",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 7 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_count{instance=~'$instance'}[$__interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Containers State",
   "type": "graph",
   "description": "The count of containers in various states",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Containers Uptime",
   "type": "table",
   "description": "Start time of the process.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "graph",
   "description": "Number of failed image builds",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 19 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(builder_builds_failed_total[$__interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "CPU per container",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\".+\"}[$__interval])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory allocation",
   "type": "table",
   "description": "Number of bytes allocated and still in use.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}