{
 "title": "Telegraf metrics",
 "description": "Prometheus/victoriametrics dashboards for telegraf metrics",
 "tags": [
  "prometheus",
  "telegraf",
  "victoriametrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "label_values(host)" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "server",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "col": "value",
     "expr": "system_uptime{host =~ \"$server$\"}",
     "measurement": "system",
     "query": "SELECT last(\"uptime\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "last" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "$server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "repeat": "server",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "col": "value",
     "expr": "quantile(0.5,mem_available_percent{host =~ \"$server$\"})",
     "measurement": "mem",
     "query": "SELECT mean(\"available_percent\") AS \"value\" FROM \"mem\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  { "title": "SYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "load1",
     "expr": "quantile(0.5,system_load1{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: load1",
     "measurement": "system",
     "query": "select mean(load1) as load1 from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "load1" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "load5",
     "expr": "quantile(0.5,system_load5{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: load5",
     "measurement": "system",
     "query": "select mean(load5) as load5 from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "load5" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "load15",
     "expr": "quantile(0.5,system_load15{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: load15",
     "measurement": "system",
     "query": "select mean(load15) as load15 from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "load15" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "total",
     "expr": "quantile(0.5,mem_total{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: total",
     "measurement": "mem",
     "query": "select mean(total) as total from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "used",
     "expr": "quantile(0.5,mem_used{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: used",
     "measurement": "mem",
     "query": "select mean(used) as used from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "cached",
     "expr": "quantile(0.5,mem_cached{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: cached",
     "measurement": "mem",
     "query": "select mean(cached) as cached from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "cached" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "free",
     "expr": "quantile(0.5,mem_free{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: free",
     "measurement": "mem",
     "query": "select mean(free) as free from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "free" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "buffered",
     "expr": "quantile(0.5,mem_buffered{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: buffered",
     "measurement": "mem",
     "query": "select mean(buffered) as buffered from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "buffered" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "idle",
     "expr": "quantile(0.5,cpu_usage_idle{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: idle",
     "measurement": "cpu",
     "query": "select mean(usage_idle) as idle from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "user",
     "expr": "quantile(0.5,cpu_usage_user{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: user",
     "measurement": "cpu",
     "query": "select mean(usage_user) as user from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "system",
     "expr": "quantile(0.5,cpu_usage_system{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: system",
     "measurement": "cpu",
     "query": "select mean(usage_system) as system from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "softirq",
     "expr": "quantile(0.5,cpu_usage_softirq{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: softirq",
     "measurement": "cpu",
     "query": "select mean(usage_softirq) as softirq from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "steal",
     "expr": "quantile(0.5,cpu_usage_steal{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: steal",
     "measurement": "cpu",
     "query": "select mean(usage_steal) as steal from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "nice",
     "expr": "quantile(0.5,cpu_usage_nice{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: nice",
     "measurement": "cpu",
     "query": "select mean(usage_nice) as nice from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "irq",
     "expr": "quantile(0.5,cpu_usage_irq{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: irq",
     "measurement": "cpu",
     "query": "select mean(usage_irq) as irq from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_irq" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "iowait",
     "expr": "quantile(0.5,cpu_usage_iowait{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: iowait",
     "measurement": "cpu",
     "query": "select mean(usage_iowait) as iowait from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "guest",
     "expr": "quantile(0.5,cpu_usage_guest{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: guest",
     "measurement": "cpu",
     "query": "select mean(usage_guest) as guest from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "guest_nice",
     "expr": "quantile(0.5,cpu_usage_guest_nice{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: guest_nice",
     "measurement": "cpu",
     "query": "select mean(usage_guest_nice) as guest_nice from \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    }
   ]
  },
  {
   "title": "Disk inodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_path : $col",
     "col": "free",
     "expr": "quantile(0.5,disk_inodes_free{host =~ \"$server$\",path=\"/host/rootfs\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: {{path}} : free",
     "measurement": "disk",
     "query": "select mean(inodes_free) as free from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "inodes_free" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path = '/'}"
    },
    {
     "alias": "$tag_host: $tag_path : $col",
     "col": "used",
     "expr": "quantile(0.5,disk_inodes_used{host =~ \"$server$\",path=\"/host/rootfs\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: {{path}} : used",
     "measurement": "disk",
     "query": "select mean(inodes_used) as used from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path = '/'}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_path : $col",
     "col": "total",
     "expr": "quantile(0.5,disk_total{host =~ \"$server$\",path=\"/host/rootfs\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: {{path}} : total",
     "measurement": "disk",
     "query": "select mean(total) AS total from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path = '/'}"
    },
    {
     "alias": "$tag_host: $tag_path : $col",
     "col": "used",
     "expr": "quantile(0.5,disk_used{host =~ \"$server$\",path=\"/host/rootfs\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: {{path}} : used",
     "measurement": "disk",
     "query": "select mean(used) as used from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path = '/'}"
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "free",
     "expr": "quantile(0.5,swap_free{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: free",
     "measurement": "swap",
     "query": "select mean(free) as free from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "free" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "used",
     "expr": "quantile(0.5,swap_used{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: used",
     "measurement": "swap",
     "query": "select mean(used) as used from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "total",
     "expr": "quantile(0.5,swap_total{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: total",
     "measurement": "swap",
     "query": "select mean(total) as total from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "in",
     "expr": "quantile(0.5,swap_in{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: in",
     "measurement": "swap",
     "query": "select mean(in) as in from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "in" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "out",
     "expr": "quantile(0.5,swap_out{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: out",
     "measurement": "swap",
     "query": "select mean(out) as out from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "out" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Swap usage (percent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "used",
     "expr": "quantile(0.5,swap_used_percent{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: used",
     "measurement": "swap",
     "query": "SELECT mean(used_percent) as used FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  { "title": "DOCKER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Total CPUs per Host",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "quantile(0.5,docker_n_cpus{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}",
     "measurement": "docker",
     "query": "SELECT mean(\"n_cpus\") FROM \"docker\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Total RAM per host",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 63 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "quantile(0.5,docker_memory_total{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}",
     "measurement": "docker",
     "query": "SELECT mean(\"memory_total\") FROM \"docker\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Containers by Host",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "docker_n_containers{host =~ \"$server$\"}",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}",
     "measurement": "docker",
     "query": "SELECT last(\"n_containers\") FROM \"docker\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "last" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "File Descriptors by host",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "quantile(0.5,docker_n_used_file_descriptors{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}",
     "measurement": "docker",
     "query": "SELECT mean(\"n_used_file_descriptors\") FROM \"docker\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "n_used_file_descriptors" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Images per host",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "quantile(0.5,docker_n_images{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}",
     "measurement": "docker",
     "query": "SELECT mean(\"n_images\") FROM \"docker\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "n_images" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "GO Routines by host",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "quantile(0.5,docker_n_goroutines{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}",
     "measurement": "docker",
     "query": "SELECT mean(\"n_goroutines\") FROM \"docker\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "n_goroutines" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "quantile(0.5,docker_container_cpu_usage_percent{host =~ \"$server$\"}) by (host,container_image)",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}",
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_cpu\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "RAM usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "quantile(0.5,docker_container_mem_usage_percent{host =~ \"$server$\"}) by (host,container_image)",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}",
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network usage by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "rate(docker_container_net_rx_bytes{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),1s)/8 as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "rate(docker_container_net_tx_bytes{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),1s)/8 as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network packets by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "rate(docker_container_net_rx_packets{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_packets\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "rate(docker_container_net_tx_packets{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_packets\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_packets" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network dropped by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "rate(docker_container_net_rx_dropped{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_dropped\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_dropped" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "rate(docker_container_net_tx_dropped{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_dropped\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_dropped" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network errors by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "rate(docker_container_net_rx_errors{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_errors\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "rate(ocker_container_net_tx_errors{host =~ \"$server$\"}[$__interval])",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_errors\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_errors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  }
 ]
}