# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: k8s.gcr.io/elasticsearch
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

transportPort: 9300

service:
  type: ClusterIP
  port: 9200

resources:
  limits:
    cpu: 1000m
  requests:
    cpu: 100m

nodeSelector:
  elastichost: "true"

pvSize: 2Gi

environment:
- name: MINIMUM_MASTER_NODES
  value: "1"
- name: "NAMESPACE"
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
