---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "elasticsearch.name" . }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvSize }}
