---
- name: Install Gitlab runner
  hosts: runners
  become: true
  vars:
    runner_name: "{{ inventory_hostname }}_{{ '%Y%m%d_%H%M%S' | strftime }}"
  tasks:
    - name: Check runner registration
      lineinfile:
        path: /etc/gitlab-runner/config.toml
        regexp: "token"
        state: absent
      check_mode: yes
      register: gitlab_config
      ignore_errors: true

    - name: debug
      debug:
        msg: "{{ gitlab_config }}"

    - name: Regiter gitlab runner
      uri:
        url: "{{ gitlab_server_proto }}://{{ gitlab_server_ip }}/api/v4/runners"
        headers:
          PRIVATE-TOKEN: "{{ gitlab_admin_token }}"
        body_format: form-urlencoded
        body:
          token: "{{ gitlab_registration_token }}"
          description: "{{ runner_name }}"
          locked: "false"
          run_untagged: "true"
          tag_list: "{{ gitlab_tags }}"
        method: POST
        timeout: 30
        status_code: [200, 201]
        return_content: yes
      when: not gitlab_config.changed
      register: gitlab_token

    - name: Copy configuration file
      template:
        src: templates/config.toml.j2
        dest: /etc/gitlab-runner/config.toml
        mode: 600
      when: gitlab_token.json is defined
      notify:
        - restart runner

  handlers:
    - name: restart runner
      service:
        name: gitlab-runner
        state: restarted
