version: '3.7'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${IMAGE_TAG_UI}
    ports:
      - ${EXT_PORT}:${INT_PORT}/tcp
    networks:
      - front_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${IMAGE_TAG_POST}
    networks:
      - back_net
      - front_net

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${IMAGE_TAG_COMMENT}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24

  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
